-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.employees
(

    CONSTRAINT emp_key PRIMARY KEY (emp_id),
    CONSTRAINT emp_dept_unique UNIQUE (emp_id, dept_id)
);

CREATE TABLE IF NOT EXISTS public.departments
(

    CONSTRAINT dept_key PRIMARY KEY (dept_id),
    CONSTRAINT dept_city_unique UNIQUE (dept, city)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id bigserial,
    role character varying,
    PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.salaries
(
    salary_id bigserial,
    salary_pa integer,
    PRIMARY KEY (salary_id)
);

CREATE TABLE IF NOT EXISTS public."overtime hours"
(
    overtime_id bigserial,
    overtime_hours integer,
    PRIMARY KEY (overtime_id)
);

ALTER TABLE IF EXISTS public.employees
    ADD CONSTRAINT employees_dept_id_fkey FOREIGN KEY (dept_id)
    REFERENCES public.departments (dept_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (emp_id)
    REFERENCES public.salaries (salary_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (emp_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."overtime hours"
    ADD FOREIGN KEY (overtime_id)
    REFERENCES public.employees (emp_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;